#pragma once
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 1
#define PERMISSIVE_HOLD
//#define FLOW_TAP_TERM 200
#define CHORDAL_HOLD
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250
#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY
