# This file intentionally left blank
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = yes
LEADER_ENABLE = yes
TAP_DANCE_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
